%% this script was created to compute the gist features for each picture
% and then write them to the .gist file and .gistfname files

clear;
clc;

modelList = {
%     'bigben',...
%     'kxm',...
%     'notredame',...
%     'freeGodness',...
%     'tajMahal',...
    'cctv3',...
    'BrandenburgGate',...
    'BritishMuseum',...
    'potalaPalace',...
    'capitol',...
    'Sacre',...
    'TengwangPavilion',...
    'mont',...
    'HelsinkiCathedral',...
    'BuckinghamPalace',...
    'castle',...
    'njuSample',...
    'njuActivity',...
    'njuSample2',...
    'njuActivity2'
%     'house8',...
%     'pavilion9',...
%     'villa7s'

    };

modelList = {    
%     'njuSample10',...
%     'njuSample12',...
    'njuSample9'};

% I think that there is no need to clear the .2dvnf and
% .2dvnfname file, because the feaCombining.py file will
% generate them again.
suffix = {
    '.gist512'
%     '.2dvnf',...
%     '.2dvnfname',...
    };

clearFiles(modelList, suffix);
disp('clear done');

tic
% load filename first
for i = 1:numel(modelList)
    fileList = fileLoad(modelList{i});
    [fea, para] = gistFeaGen(fileList);
%     fea = vanishFeaGen(fileList);
%     write features to files
    writeFea(modelList{i}, fileList, fea, suffix{1});
    disp(['gistFeaGen done ' modelList{i}])
end
toc
