%% this script was created to plot classify error bar
% just for combine classify
clear
close all
clc
time = tic;
addpath('../');
addpath('../fisherVector/')
addpath('./svm2k')

modelList = {
    'bigben',...
    'kxm',...
    'notredame',...
    'freeGodness',...
    'tajMahal',...
    'cctv3',...
    'capitol',...
    'Sacre',...
    'TengwangPavilion',...
    'mont',...
    'HelsinkiCathedral',...
    'BuckinghamPalace',...
    'BritishMuseum',...
    'BrandenburgGate',...
    'potalaPalace'
};

% top rate pictures will be assign good
% last rate pictures will be assign bad
% this parameters should bbe modified as needed
rate = 0.10;
% load Data
% sc = scload(scorefile,sceneName);
[sc,scr,fea2d,fea3d] = dataLoad(modelList);
[fsAll,fname] = combine(fea2d,fea3d,scr);
[fs2dAll,fname] = combine(fea2d,scr);
[fs3dAll,fname] = combine(fea3d,scr);

amtErrorRateBarClassify;
