function createlegend(axes,feaName)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 13-May-2016 22:33:05

for i=1:length(feaName)
	fN{i} = feaName{i}.name;
end

% Create legend
% legend1 = legend(axes1,fN,'show','Location','southeast');
% legend1 = legend(axes,fN,'Location','southeast');
legend1 = legend(axes,'show');
set(legend1,...
    'Position',[0.772380954254241 0.320476194946539 0.142857140983854 0.163333328862985]);

