%% this file was the clustering start file
modelList = {
    'bigben',...
    'kxm',...
    'notredame',...
    'freeGodness',...
    'tajMahal',...
    'cctv3',...
    'BrandenburgGate',...
    'BritishMuseum',...
    'potalaPalace',...
    'capitol',...
    'Sacre',...
    'TengwangPavilion',...
    'mont',...
    'HelsinkiCathedral',...
    'BuckinghamPalace'    
};

for i = 1:numel(modelList)
    mvDist(modelList{i})
end