%% this file was created for just debug
% for i=1:size(clusterCenter,1)
%        index = cluster == i;
%        tmpPs = ps(index,:);
%        psCenter = mean(tmpPs,1);
%         fprintf(fid,'%f %f %f %f %f %f %f %f %f\n',psCenter(1),...
%             psCenter(2),...
%             0,...
%             clusterCenter(i,4),...
%             clusterCenter(i,5),...
%             clusterCenter(i,6),...
%             clusterCenter(i,7),...
%             clusterCenter(i,8),...
%             clusterCenter(i,9));
%     end

% modelList = {
% %     'capitol',...
% %     'TengwangPavilion',...
% %     'mont',...
% %     'HelsinkiCathedral',...
%     'Sacre',...
%     'BuckinghamPalace',...
%     'BrandenburgGate',...
%     'notredame',...
%     'capitol'
% %     'freeGodness',...
% %     'potalaPalace'
%     };
% 
% %     'cctv3',...
% %     'kxm',...
%     
% %     'bigben',...
% %     'freeGodness',...
% %     'tajMahal',...

modelList = {'capitol'};

for i = 1:numel(modelList)
    mvDist(modelList{i});
end

