%% this file was created to valid viewpoint preference
%{
1. analysis viewpoint preference by numerical
2. analysis viewpoint preference by cluster graph
%}

addpath ./vpval/
addpath ../amtclassify/

close all
clear
clc
rate = 0.2;

% modelList = {
%     'bigben',...
%     'kxm',...
%     'notredame',...
%     'freeGodness',...
%     'tajMahal',...
%     'cctv3',...
%     'capitol',...
%     'Sacre',...
%     'TengwangPavilion',...
%     'mont',...
%     'HelsinkiCathedral',...
%     'BuckinghamPalace',...
%     'BritishMuseum',...
%     'BrandenburgGate',...
%     'potalaPalace'
%     };
model = {'BrandenburgGate'};

numericalVpval;


% 1 0.6
% 2 0.63636
% 3 0.44444
% 4 0.38462
% 5 0.61111
% 6 0.77778